//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE_CONTACTOS
    {
        public int CONTACTO_ID { get; set; }
        public int CLIENTE_ID { get; set; }
        public int NUMERO_CONTACTO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
